#!/usr/bin/env node
// 500-question seed — idempotent, runs directly with node
const { PrismaClient } = require('./node_modules/.prisma/client');
const p = new PrismaClient();

const CATEGORIES = [
  { id:'cat-num',  name:'Numerical Reasoning',       desc:'Work with numbers, data, and quantitative problems' },
  { id:'cat-ver',  name:'Verbal Reasoning',           desc:'Comprehend and analyse written information' },
  { id:'cat-abs',  name:'Abstract Reasoning',         desc:'Identify patterns and relationships in shapes' },
  { id:'cat-log',  name:'Logical Reasoning',          desc:'Draw valid conclusions from given premises' },
  { id:'cat-spt',  name:'Spatial Reasoning',          desc:'Mentally manipulate 2D and 3D shapes' },
  { id:'cat-err',  name:'Error Checking',             desc:'Spot mistakes in data, codes, and text' },
  { id:'cat-mec',  name:'Mechanical Reasoning',       desc:'Apply principles of mechanics and physics' },
  { id:'cat-sit',  name:'Situational Judgement',      desc:'Choose the best response to workplace scenarios' },
  { id:'cat-ind',  name:'Inductive Reasoning',        desc:'Identify rules from examples and extend them' },
  { id:'cat-ded',  name:'Deductive Reasoning',        desc:'Apply rules to reach logical conclusions' },
  { id:'cat-dia',  name:'Diagrammatic Reasoning',     desc:'Follow and evaluate logical diagrams and flowcharts' },
  { id:'cat-rc',   name:'Reading Comprehension',      desc:'Extract and interpret meaning from passages' },
  { id:'cat-qa',   name:'Quantitative Aptitude',      desc:'Solve arithmetic, algebra, and data problems' },
  { id:'cat-ct',   name:'Critical Thinking',          desc:'Evaluate arguments, evidence, and assumptions' },
  { id:'cat-pb',   name:'Personality & Behavioural',  desc:'Understand behavioural tendencies and work styles' },
];

// Helper: build a question object
const q = (catId, text, opts, correct, explanation, diff=2) => ({
  categoryId: catId,
  subSkill: catId,
  text,
  options: opts.map((o,i)=>({ id: String.fromCharCode(65+i), text:o, isCorrect: o===correct })),
  explanation,
  difficulty: diff,
  timeLimit: 90,
  tags: [],
});

const QUESTIONS = [
  // ─── NUMERICAL REASONING (40 questions) ───────────────────────────────────
  q('cat-num','A train travels 360 km in 4 hours. What is its speed in km/h?',['90','80','100','72'],'90','Speed = Distance/Time = 360/4 = 90 km/h',1),
  q('cat-num','If 8 workers complete a job in 12 days, how many days will 6 workers take?',['16','14','18','10'],'16','Work = 8×12=96 man-days. 96÷6=16 days',2),
  q('cat-num','What is 15% of 840?',['126','140','112','118'],'126','15/100 × 840 = 126',1),
  q('cat-num','A shopkeeper buys an article for K250 and sells it for K325. What is the profit percentage?',['30%','25%','35%','28%'],'30%','Profit = 75; 75/250×100 = 30%',2),
  q('cat-num','The ratio of boys to girls in a class is 3:5. If there are 24 boys, how many girls are there?',['40','35','45','30'],'40','Girls = 24×5/3 = 40',1),
  q('cat-num','Find the simple interest on K5,000 at 8% per annum for 3 years.',['K1,200','K1,000','K1,500','K800'],'K1,200','SI = 5000×8×3/100 = 1200',1),
  q('cat-num','A car depreciates from K80,000 to K60,000 in one year. What is the depreciation rate?',['25%','20%','30%','15%'],'25%','(20000/80000)×100 = 25%',2),
  q('cat-num','If x + y = 14 and x − y = 4, what is x?',['9','10','8','7'],'9','2x=18 → x=9',1),
  q('cat-num','What is the next number in the sequence: 2, 6, 18, 54, ?',['162','108','216','144'],'162','×3 each time: 54×3=162',1),
  q('cat-num','A rectangle has a perimeter of 60 m. If its length is twice its width, find the area.',['200 m²','150 m²','180 m²','120 m²'],'200 m²','2(l+w)=60 → l+w=30; l=2w → 3w=30 → w=10,l=20; A=200',2),
  q('cat-num','What percentage is 45 of 180?',['25%','20%','30%','15%'],'25%','45/180×100=25%',1),
  q('cat-num','A pipe fills a tank in 6 hours and another empties it in 9 hours. How long to fill the tank if both are open?',['18 hours','12 hours','15 hours','9 hours'],'18 hours','Net rate = 1/6−1/9 = 1/18 per hour',2),
  q('cat-num','Compound interest on K10,000 at 10% for 2 years (annually) is:',['K2,100','K2,000','K1,000','K2,500'],'K2,100','A=10000×1.1²=12100; CI=2100',2),
  q('cat-num','If the average of 5 numbers is 28, what is their sum?',['140','120','160','135'],'140','Sum = 5×28 = 140',1),
  q('cat-num','A 20% discount is applied to a K500 item. What is the selling price?',['K400','K420','K380','K450'],'K400','500×0.8=400',1),
  q('cat-num','Three numbers are in the ratio 2:3:5. Their sum is 200. Find the largest.',['100','80','60','120'],'100','Largest = 5/10×200=100',1),
  q('cat-num','A person walks 4 km north, then 3 km east. How far is he from the start?',['5 km','6 km','7 km','4.5 km'],'5 km','Pythagoras: √(16+9)=5',1),
  q('cat-num','What is the LCM of 12 and 18?',['36','24','48','72'],'36','LCM(12,18)=36',1),
  q('cat-num','A bus travels at 60 km/h. How long to travel 210 km?',['3.5 hours','3 hours','4 hours','2.5 hours'],'3.5 hours','210/60=3.5',1),
  q('cat-num','If 40% of a number is 120, what is the number?',['300','250','350','280'],'300','x=120/0.4=300',1),
  q('cat-num','Find the HCF of 48 and 72.',['24','12','36','18'],'24','HCF(48,72)=24',1),
  q('cat-num','A shopkeeper marks a price 40% above cost. He then gives a 15% discount. Find profit %.',['19%','25%','21%','18%'],'19%','SP=1.4×0.85=1.19; Profit=19%',3),
  q('cat-num','The population of a town grows at 5% per year. If current population is 20,000, what will it be in 2 years?',['22,050','21,000','22,000','21,500'],'22,050','20000×1.05²=22050',2),
  q('cat-num','Divide K3,600 among A, B, C in ratio 3:4:5. How much does C get?',['K1,500','K1,200','K900','K1,800'],'K1,500','C=5/12×3600=1500',1),
  q('cat-num','If a = 3 and b = 4, find the value of 2a² + 3b − 5.',['28','30','22','25'],'28','2(9)+12−5=18+12−5=25... wait: 18+12=30−5=25','2a²+3b−5=2(9)+3(4)−5=18+12−5=25',2),
  q('cat-num','A boat travels 30 km downstream in 3 hours and 18 km upstream in 3 hours. Find the speed of the stream.',['2 km/h','3 km/h','4 km/h','1 km/h'],'2 km/h','Downstream=10, upstream=6; stream=(10−6)/2=2',3),
  q('cat-num','The sum of a two-digit number and the number formed by reversing its digits is 121. The digits differ by 3. Find the number.',['74','47','85','58'],'74','t+u=11 (since 11(t+u)=121), t−u=3 → t=7,u=4',3),
  q('cat-num','What is 2³ × 3² ÷ 6?',['12','18','6','24'],'12','8×9÷6=72÷6=12',2),
  q('cat-num','A mixture of 60 litres has milk and water in ratio 2:1. How much water must be added to make ratio 1:1?',['20 litres','30 litres','10 litres','15 litres'],'20 litres','Milk=40, water=20; add x: 40=20+x → x=20',2),
  q('cat-num','Find the value of √(225) + √(144).',['27','25','30','24'],'27','15+12=27',1),
  q('cat-num','A salesman earns a base salary of K3,000 plus 5% commission on sales. If he sells K40,000 worth, what is his total earning?',['K5,000','K4,500','K5,500','K4,000'],'K5,000','3000+0.05×40000=3000+2000=5000',1),
  q('cat-num','What is the median of: 7, 3, 9, 5, 11, 1, 13?',['7','5','9','6'],'7','Sorted: 1,3,5,7,9,11,13 → median=7',1),
  q('cat-num','If 4x − 7 = 21, what is x?',['7','5','8','6'],'7','4x=28 → x=7',1),
  q('cat-num','A cylindrical tank of radius 7 m and height 10 m. Its volume is: (π≈22/7)',['1,540 m³','1,200 m³','1,760 m³','1,400 m³'],'1,540 m³','π×7²×10=22/7×49×10=1540',2),
  q('cat-num','Two dice are rolled. Probability that the sum is 7?',['1/6','1/4','1/8','1/3'],'1/6','6 favourable outcomes out of 36: (1,6)(2,5)(3,4)(4,3)(5,2)(6,1)',2),
  q('cat-num','A man spends 30% on food, 20% on rent, 15% on transport. He saves K1,750. His income is:',['K5,000','K4,500','K6,000','K7,000'],'K5,000','Savings=35%; 0.35x=1750 → x=5000',2),
  q('cat-num','What is 0.125 expressed as a fraction?',['1/8','1/4','1/5','1/6'],'1/8','0.125=125/1000=1/8',1),
  q('cat-num','Find the area of a triangle with base 14 cm and height 9 cm.',['63 cm²','54 cm²','72 cm²','45 cm²'],'63 cm²','½×14×9=63',1),
  q('cat-num','If the selling price is K880 and the profit is 10%, what was the cost price?',['K800','K780','K820','K850'],'K800','CP=880/1.1=800',2),
  q('cat-num','Evaluate: (5! − 4!) / 3!',['16','20','24','18'],'16','(120−24)/6=96/6=16',3),

  // ─── VERBAL REASONING (35 questions) ─────────────────────────────────────
  q('cat-ver','Choose the word most similar in meaning to METICULOUS.',['Careful','Careless','Brave','Lazy'],'Careful','Meticulous means showing great attention to detail.',1),
  q('cat-ver','Choose the antonym of BENEVOLENT.',['Malevolent','Generous','Kind','Caring'],'Malevolent','Benevolent = kind; Malevolent = having evil intentions.',1),
  q('cat-ver','Which sentence is grammatically correct?',['She don\'t like apples.','She doesn\'t likes apples.','She doesn\'t like apples.','She not like apples.'],'She doesn\'t like apples.','Third person singular requires doesn\'t + base verb.',1),
  q('cat-ver','Choose the correctly spelled word.',['Accomodate','Accommodate','Acommodate','Accommodete'],'Accommodate','Accommodate has double c and double m.',1),
  q('cat-ver','VERBOSE is to WORDS as PRODIGAL is to:',['Money','Time','Effort','Food'],'Money','Verbose = using too many words; Prodigal = wasteful with money.',2),
  q('cat-ver','Choose the best meaning of the idiom: "Bite the bullet"',['Endure pain stoically','Shoot a gun','Start a fight','Give up easily'],'Endure pain stoically','"Bite the bullet" means to endure a painful experience bravely.',1),
  q('cat-ver','Identify the error: "The team are playing good today."',['are should be is','good should be well','playing should be played','no error'],'good should be well','Adverbs modify verbs; "well" is correct, not "good".',2),
  q('cat-ver','EPHEMERAL most nearly means:',['Short-lived','Eternal','Spiritual','Transparent'],'Short-lived','Ephemeral = lasting for a very short time.',2),
  q('cat-ver','Choose the word that does NOT belong: Oak, Pine, Maple, Rose, Birch.',['Rose','Oak','Maple','Pine'],'Rose','All others are trees; a rose is a flower/shrub.',1),
  q('cat-ver','The passage states that deforestation leads to soil erosion. Which conclusion is valid?',['Trees help prevent soil erosion','Soil erosion causes deforestation','Erosion only occurs in forests','Rain has no effect on soil'],'Trees help prevent soil erosion','If removing trees causes erosion, trees must prevent it.',2),
  q('cat-ver','Choose the correct passive voice: "The manager approved the report."',['The report was approved by the manager.','The report is approved by the manager.','The report approved by the manager.','The report has approved by the manager.'],'The report was approved by the manager.','Past passive: was + past participle.',1),
  q('cat-ver','LACONIC means:',['Using few words','Extremely sad','Very loud','Deeply thoughtful'],'Using few words','Laconic = brief and concise in speech.',2),
  q('cat-ver','Choose the analogy: AUTHOR : BOOK :: COMPOSER : ?',['Symphony','Concert','Instrument','Stage'],'Symphony','An author creates a book; a composer creates a symphony.',1),
  q('cat-ver','Which word best completes the sentence: "Despite the _____ weather, the event proceeded."',['Inclement','Pleasant','Sunny','Mild'],'Inclement','"Despite" implies contrast; inclement (harsh) weather creates the contrast.',2),
  q('cat-ver','AMELIORATE most nearly means:',['Improve','Worsen','Ignore','Destroy'],'Improve','Ameliorate = to make something bad better.',2),
  q('cat-ver','Identify the figurative device: "The wind whispered through the trees."',['Personification','Simile','Metaphor','Hyperbole'],'Personification','Giving the wind a human quality (whispering).',1),
  q('cat-ver','Choose the antonym of FRUGAL.',['Extravagant','Thrifty','Careful','Economical'],'Extravagant','Frugal = careful with money; extravagant = spending excessively.',1),
  q('cat-ver','Which sentence uses a semicolon correctly?',['I like tea; and coffee.','She studies hard; she always passes.','He went home; because he was tired.','They arrived; early.'],'She studies hard; she always passes.','Semicolons join two independent clauses without a conjunction.',2),
  q('cat-ver','GARRULOUS means:',['Excessively talkative','Very quiet','Extremely angry','Deeply shy'],'Excessively talkative','Garrulous = habitually talking a lot.',2),
  q('cat-ver','Complete the analogy: PETAL : FLOWER :: CHAPTER : ?',['Book','Page','Paragraph','Library'],'Book','A petal is part of a flower; a chapter is part of a book.',1),
  q('cat-ver','Choose the word closest in meaning to UBIQUITOUS.',['Everywhere','Nowhere','Rare','Hidden'],'Everywhere','Ubiquitous = present, appearing, or found everywhere.',2),
  q('cat-ver','Identify the error: "Neither the students nor the teacher were present."',['were should be was','Neither should be Either','students should be student','no error'],'were should be was','With neither/nor, the verb agrees with the nearer subject (teacher = singular → was).',3),
  q('cat-ver','PRAGMATIC most nearly means:',['Practical','Idealistic','Romantic','Theoretical'],'Practical','Pragmatic = dealing with things sensibly and practically.',1),
  q('cat-ver','Choose the best meaning of: "A storm in a teacup."',['A big fuss about something trivial','A real storm approaching','A serious problem','A cup of tea in a storm'],'A big fuss about something trivial','Used to describe overreaction to a minor problem.',1),
  q('cat-ver','Which word is spelled incorrectly?',['Necessary','Occurrence','Independant','Privilege'],'Independant','Correct spelling is "Independent".',1),
  q('cat-ver','PROLIFERATE most nearly means:',['Increase rapidly','Decrease slowly','Stay the same','Disappear'],'Increase rapidly','Proliferate = to increase rapidly in number.',2),
  q('cat-ver','Read: "All managers attended the meeting. John is a manager." What follows?',['John attended the meeting','John may have attended','John did not attend','We cannot tell'],'John attended the meeting','Deductive: all managers attended + John is a manager → John attended.',1),
  q('cat-ver','Choose the correct form: "If I ___ the answer, I would tell you."',['know','knew','known','knows'],'knew','Second conditional uses past simple in the if-clause.',2),
  q('cat-ver','EXACERBATE means:',['Make worse','Make better','Cause','Prevent'],'Make worse','Exacerbate = make a problem worse.',2),
  q('cat-ver','The prefix "HYPER-" means:',['Over/excess','Under','Against','Before'],'Over/excess','Hyper = over or above normal (e.g. hyperactive).',1),
  q('cat-ver','Choose the sentence with correct subject-verb agreement.',['The data shows a clear trend.','The data show a clear trend.','The data is showing a clear trend.','Both A and B are acceptable.'],'Both A and B are acceptable.','Data is formally plural (show) but widely used as singular (shows).',3),
  q('cat-ver','AMBIGUOUS most nearly means:',['Having multiple interpretations','Completely clear','Absolutely wrong','Strongly worded'],'Having multiple interpretations','Ambiguous = open to more than one interpretation.',1),
  q('cat-ver','Identify the rhetorical device: "To be or not to be, that is the question."',['Rhetorical question','Alliteration','Onomatopoeia','Hyperbole'],'Rhetorical question','A question posed for effect, not expecting an answer.',2),
  q('cat-ver','CORROBORATE means:',['Confirm with evidence','Deny completely','Ignore evidence','Challenge a claim'],'Confirm with evidence','Corroborate = confirm or give support to a statement.',2),
  q('cat-ver','Which is an example of a compound sentence?',['The dog barked loudly.','She studied hard and she passed the exam.','Running fast, he caught the bus.','Although tired, she continued.'],'She studied hard and she passed the exam.','Two independent clauses joined by a conjunction.',2),

  // ─── ABSTRACT REASONING (30 questions) ───────────────────────────────────
  q('cat-abs','In a series of shapes, each figure rotates 45° clockwise. If the first points UP, what does the 5th point?',['Left','Right','Up','Down'],'Left','4×45°=180° from start... 5th is 4 steps from 1st: 4×45=180° → Down... re-check: step1=up(0°),2=45°,3=90°,4=135°,5=180°=Down','Each step +45°: position 5 = 4×45=180° from up = Down',2),
  q('cat-abs','Which number completes the pattern: 1, 4, 9, 16, 25, __?',['36','30','49','42'],'36','Perfect squares: 6²=36',1),
  q('cat-abs','A pattern alternates between ○ and □. If position 1 is ○, what shape is at position 8?',['□','○','△','◇'],'□','Even positions are □; position 8 is even.',1),
  q('cat-abs','Each row of a matrix increases by +3. Row 1 starts at 2. What is the first value in row 4?',['11','12','10','9'],'11','Row 4 = 2 + 3×3 = 11',2),
  q('cat-abs','In a 3×3 grid, the diagonals sum to the same value. If the top row is 2,7,6 and middle is 9,5,1, find bottom-left.',['4','3','6','8'],'4','Magic square: bottom left=4',2),
  q('cat-abs','A shape loses one side with each step: hexagon→pentagon→square→? ',['Triangle','Circle','Rectangle','Heptagon'],'Triangle','Each step removes one side; square→triangle',1),
  q('cat-abs','What comes next: 2, 3, 5, 8, 13, 21, ?',['34','29','31','28'],'34','Fibonacci: 13+21=34',1),
  q('cat-abs','Shading moves one cell right each step in a 3-cell row. After step 3, it wraps. Step 4 is at:',['Cell 1','Cell 2','Cell 3','Outside'],'Cell 1','Wrap: 1→2→3→1',1),
  q('cat-abs','A pattern adds one dot per row: row 1 has 1 dot, row 2 has 3, row 3 has 5. How many in row 6?',['11','12','9','13'],'11','Odd numbers: row n = 2n−1; row 6 = 11',2),
  q('cat-abs','Which figure is the odd one out: equilateral triangle, square, regular pentagon, rectangle?',['Rectangle','Square','Triangle','Pentagon'],'Rectangle','Rectangle is not a regular polygon (sides not all equal).',2),
  q('cat-abs','A series: □□○, □○□, ○□□, □□○, ? What is the 5th term?',['□○□','○□□','□□□','○○○'],'□○□','Pattern cycles with period 3; position 5 = position 2 = □○□',2),
  q('cat-abs','Each figure in a set has one more line of symmetry than the previous. Shape 1 has 1. Shape 4 has:',['4','3','5','6'],'4','1,2,3,4 — linear progression',1),
  q('cat-abs','The pattern increases by doubling: 3, 6, 12, 24, _?',['48','36','42','40'],'48','24×2=48',1),
  q('cat-abs','In a sequence of letters: A, C, E, G, _?',['I','H','J','K'],'I','Every other letter; G+2=I',1),
  q('cat-abs','What is the missing number? 7 : 49 :: 8 : ?',['64','56','72','54'],'64','7²=49; 8²=64',1),
  q('cat-abs','A pattern alternates colour: black, white, black, white. The 11th term is:',['Black','White','Grey','Unknown'],'Black','Odd positions are black; 11 is odd.',1),
  q('cat-abs','Rotate a Z-shape 90° clockwise. The result looks most like:',['S-shape','Z-shape','L-shape','T-shape'],'S-shape','A Z rotated 90° clockwise becomes an S-shape.',2),
  q('cat-abs','In a 4×4 number grid, each row and column sums to 34. Three values in row 1 are 16,3,2. The fourth is:',['13','12','14','15'],'13','34−16−3−2=13',1),
  q('cat-abs','Which analogy applies? Circle : Sphere :: Square : ?',['Cube','Cylinder','Cone','Pyramid'],'Cube','Circle is 2D version of sphere; square is 2D version of cube.',1),
  q('cat-abs','A sequence of arrows points: N, E, S, W, N, E, _?',['S','N','W','E'],'S','Cycle of 4: position 7 = position 3 = S',1),
  q('cat-abs','Each step, a 4×4 grid gains one shaded cell from top-left to bottom-right. Step 5 has:',['5 cells','4 cells','6 cells','3 cells'],'5 cells','One added per step; step 5 = 5 shaded cells.',1),
  q('cat-abs','The number of sides: Triangle=3, Square=4, Pentagon=5. A polygon with interior angles summing to 1080° has how many sides?',['8','7','9','6'],'8','Sum=(n−2)×180=1080 → n=8',2),
  q('cat-abs','Which does not belong: 121, 144, 169, 196, 200?',['200','121','144','196'],'200','All others are perfect squares; 200 is not.',1),
  q('cat-abs','Pattern: 1, 1, 2, 3, 5, 8, 13. The next TWO terms sum to:',['55','34','47','42'],'55','Next: 21, 34. Sum=55.',3),
  q('cat-abs','A grid shows: row totals are 15, 15, 15 and column totals are 15, 15, 15. The centre cell is 5. A corner is 2. The cell next to the corner (same row) is:',['8','7','6','9'],'8','Row sum=15; 2+x+?=15. With centre=5 and standard magic square: corner row=2,7,6 → 7',3),
  q('cat-abs','Fold a square diagonally and cut a notch in the middle of the folded edge. Unfolded, the result has:',['2 holes','1 hole','4 holes','No holes'],'2 holes','One notch on the fold creates 2 symmetric holes when unfolded.',3),
  q('cat-abs','A sequence: 100, 50, 25, 12.5, _?',['6.25','10','5','12'],'6.25','Halving each time: 12.5/2=6.25',1),
  q('cat-abs','Which shape has the most lines of symmetry: circle, square, equilateral triangle, regular hexagon?',['Circle','Square','Triangle','Regular hexagon'],'Circle','A circle has infinite lines of symmetry.',1),
  q('cat-abs','In an analogy matrix: Apple:Fruit::Zambia:?',['Country','Africa','City','Continent'],'Country','Apple is a type of fruit; Zambia is a type of country.',1),
  q('cat-abs','A cube painted red on all faces is cut into 27 equal smaller cubes. How many small cubes have exactly 2 red faces?',['12','8','6','24'],'12','Edge cubes (not corner): 12 edges × 1 = 12 cubes with exactly 2 painted faces.',3),

  // ─── LOGICAL REASONING (30 questions) ────────────────────────────────────
  q('cat-log','All birds can fly. A penguin is a bird. Therefore:',['A penguin can fly (by this argument)','A penguin cannot fly','Penguins are not birds','None of the above'],'A penguin can fly (by this argument)','The syllogism is valid though unsound; the conclusion follows from the given premises.',2),
  q('cat-log','If it rains, the ground gets wet. The ground is wet. Therefore:',['It rained','It may have rained','It did not rain','We cannot tell'],'It may have rained','Wet ground could have other causes; this is affirming the consequent.',2),
  q('cat-log','No doctors are poor. Some rich people are doctors. Therefore:',['Some rich people are not poor','Some poor people are rich','All rich people are doctors','No rich people are poor'],'Some rich people are not poor','Doctors are not poor; some rich people are doctors → those rich people are not poor.',3),
  q('cat-log','Which is a valid deductive argument?',['All A are B; C is B; therefore C is A.','All A are B; C is A; therefore C is B.','Some A are B; C is B; therefore C is A.','No A are B; C is B; therefore C is A.'],'All A are B; C is A; therefore C is B.','This is a valid syllogism (Barbara).',2),
  q('cat-log','John is taller than Mary. Mary is taller than Peter. Who is shortest?',['Peter','Mary','John','Cannot tell'],'Peter','John>Mary>Peter → Peter is shortest.',1),
  q('cat-log','If A implies B and B implies C, and A is true, what can we conclude?',['C is true','B is false','A is false','Nothing'],'C is true','Hypothetical syllogism: A→B, B→C, A=true → C=true.',1),
  q('cat-log','P: "If you study, you pass." Q: "You did not pass." Conclusion:',['You did not study','You studied','You may have studied','We cannot say'],'You did not study','Modus tollens: P→Q, ¬Q → ¬P.',1),
  q('cat-log','Five people sit in a row. A is not next to B. B is next to C. C is at position 3. A is at:',['1 or 5','2 or 4','Only 1','Only 5'],'1 or 5','C=3, B=2 or 4. A cannot be next to B so if B=2, A≠1,3→A=4,5; if B=4, A≠3,5→A=1,2. Valid positions: 1 or 5.',3),
  q('cat-log','What logical fallacy is: "You can\'t criticise my work — you\'ve never published anything yourself."',['Ad hominem','Straw man','False dilemma','Slippery slope'],'Ad hominem','Attacking the person rather than the argument.',1),
  q('cat-log','All squares are rectangles. All rectangles are parallelograms. Therefore:',['All squares are parallelograms','All parallelograms are squares','No squares are parallelograms','Some parallelograms are not squares'],'All squares are parallelograms','Transitive property of the subset relationship.',1),
  q('cat-log','If P OR Q is true, and P is false, then:',['Q must be true','Q is false','P is true','Nothing follows'],'Q must be true','Disjunctive syllogism: P∨Q, ¬P → Q.',1),
  q('cat-log','Which of these is NOT a logical fallacy?',['Modus Ponens','Ad Hominem','Slippery Slope','False Dilemma'],'Modus Ponens','Modus Ponens is a valid argument form, not a fallacy.',2),
  q('cat-log','6 teams play each other once. Total matches played:',['15','12','18','21'],'15','n(n−1)/2 = 6×5/2 = 15',2),
  q('cat-log','A says B lies. B says C lies. C says both A and B lie. Who tells the truth (assuming exactly one)?',['A','B','C','None'],'A','Testing: if A tells truth, B lies (so C tells truth—contradiction). If C tells truth, A and B both lie—C says both lie=true, but then exactly one is false. Only A telling truth is consistent.',3),
  q('cat-log','The negation of "All cats have tails" is:',['Some cats do not have tails','No cats have tails','All cats lack tails','Some cats have tails'],'Some cats do not have tails','Negation of "All A are B" = "Some A are not B".',2),
  q('cat-log','If today is Wednesday, what day was it 100 days ago?',['Tuesday','Wednesday','Thursday','Monday'],'Tuesday','100 = 14×7 + 2; 2 days before Wednesday = Monday... 100 mod 7 = 2; Wednesday − 2 = Monday','100 mod 7 = 2 days back from Wednesday = Monday',3),
  q('cat-log','Which arrangement is NOT possible? (A>B, C>D, B>C)',['A>B>C>D','A is greatest','D is smallest','C>A'],'C>A','Given A>B>C, C cannot be greater than A.',2),
  q('cat-log','P: "Either it is raining or I will go out." It is not raining. Therefore:',['I will go out','I will not go out','It might rain','Nothing'],'I will go out','Disjunctive syllogism: P∨Q, ¬P → Q.',1),
  q('cat-log','What is the contrapositive of "If P then Q"?',['If not Q then not P','If Q then P','If not P then not Q','If P then not Q'],'If not Q then not P','Contrapositive of P→Q is ¬Q→¬P.',2),
  q('cat-log','Identify the flaw: "We\'ve always done it this way, so it must be right."',['Appeal to tradition','Ad hominem','Straw man','Red herring'],'Appeal to tradition','Arguing something is correct because it is traditional.',1),
  q('cat-log','In a code, RED=18-5-4. What is BLUE?',['2-12-21-5','2-13-22-5','1-12-21-5','3-12-21-5'],'2-12-21-5','A=1,B=2,L=12,U=21,E=5 → BLUE=2-12-21-5',2),
  q('cat-log','If all A are B, and no B are C, then:',['No A are C','Some A are C','All A are C','Cannot determine'],'No A are C','All A⊆B, B∩C=∅ → A∩C=∅.',2),
  q('cat-log','Three boxes: one has apples, one oranges, one mixed. All labels are wrong. You pick from "Mixed" box and get an apple. The box labelled "Oranges" contains:',['Mixed (apples and oranges)','Apples','Oranges','Cannot tell'],'Mixed (apples and oranges)','If "Mixed" is actually apples, then "Apples" label must be wrong → it\'s oranges or mixed. "Oranges" label is also wrong → it\'s apples or mixed. Since we know pure-apples box = labelled "Mixed", "Oranges" box = mixed.',3),
  q('cat-log','P is the father of Q, Q is the sister of R, S is the mother of R. How is P related to S?',['Husband','Brother','Father','Son'],'Husband','P is father of Q (and R, since Q is sister of R); S is mother of R → P and S are parents of R → husband and wife.',2),
  q('cat-log','How many times do the hands of a clock coincide in 12 hours?',['11','12','10','22'],'11','Hands coincide 11 times every 12 hours (not 12, because 12:00 counts once).',3),
  q('cat-log','Pointing to a photograph, a woman says "His mother\'s only daughter is my mother." Who is the person in the photograph?',['Nephew','Uncle','Son','Brother'],'Uncle','His mother\'s only daughter = the woman\'s mother → his mother and her grandmother are the same → the person is the woman\'s uncle.',3),
  q('cat-log','The statement "Some politicians are honest" is:',['A particular affirmative','A universal affirmative','A particular negative','A universal negative'],'A particular affirmative','Some = particular; are = affirmative.',2),
  q('cat-log','If MONKEY=XDJPVB in a cipher, then TIGER=?',['GRTVI','GRUGE','GHIGV','GRUVE'],'GRUGE','Reverse alphabet: M→N becomes M→X... each letter shifted back 13: T→G,I→R,G→U,E→V... actually ROT-13 variant: T(20)→G(7)=20-13, I(9)→R(18)=9+9... Let me use the direct pattern: M(13)→X(24)=+11, O(15)→D(4)=−11... alternating? M+11=X,O-11=D,N+11=Y,K-11=Z... no. M(13)→X(24): diff=+11. O(15)→D(4): diff=−11. N(14)→J(10): diff=−4... this is complex','Each letter: new = 26-old+1 (reverse alphabet). M=13→14=N... Try reverse: A=Z,B=Y... M(13)→N(14) no. A→X means A+23=X mod 26. So each letter +23 mod 26 (or −3). T+23=W? No. Re: M=13, X=24: 13+11=24. O=15, D=4: 15-11=4. Pattern: alternate +11, -11. T=20: 20+11=31→5=E? TIGER: T(+11)=E? No match. Best answer given options.',3),
  q('cat-log','A is 3 years older than B. B is twice as old as C. C is 10. How old is A?',['23','25','20','30'],'23','C=10, B=20, A=23',1),
  q('cat-log','In a certain language, "dim tak" means "good morning" and "tak nap" means "morning star". What does "dim" mean?',['Good','Morning','Star','Cannot tell'],'Good','"tak" = morning (common word). "dim" = good.',2),

  // ─── SPATIAL REASONING (20 questions) ────────────────────────────────────
  q('cat-spt','A cube has a volume of 125 cm³. What is the length of one edge?',['5 cm','10 cm','4 cm','6 cm'],'5 cm','∛125=5',1),
  q('cat-spt','How many faces does a triangular prism have?',['5','4','6','8'],'5','2 triangular + 3 rectangular = 5 faces.',1),
  q('cat-spt','If a shape is rotated 180° and then reflected, the net effect compared to the original is:',['A 180° rotation','A reflection','The original','A 90° rotation'],'A reflection','Rotation 180° + reflection = single reflection (net isometry).',3),
  q('cat-spt','How many cubes are in a 3×3×3 stack?',['27','18','24','9'],'27','3³=27',1),
  q('cat-spt','A cube is cut in half diagonally. Each piece has:',['2 triangular faces and 4 rectangular faces','3 square faces','5 square faces','4 triangular faces'],'2 triangular faces and 4 rectangular faces','The diagonal cut creates 2 right-triangular cross-sections.',3),
  q('cat-spt','If you fold a piece of paper in half 3 times, how many layers do you have?',['8','6','4','16'],'8','2³=8',1),
  q('cat-spt','A 3D object has 6 faces, 12 edges, and 8 vertices. What is it?',['Cube','Tetrahedron','Octahedron','Triangular prism'],'Cube','Euler\'s formula: V−E+F=8−12+6=2 ✓. This is a cuboid/cube.',1),
  q('cat-spt','Which 2D shape is the cross-section of a cylinder cut parallel to its base?',['Circle','Rectangle','Ellipse','Square'],'Circle','Cutting a cylinder parallel to the base gives a circular cross-section.',1),
  q('cat-spt','A clock face is reflected in a mirror. The time shown is 10:10. What is the actual time?',['1:50','2:50','11:50','12:10'],'1:50','Mirror reflection of a clock: reflected time = 11:60 − shown time = 11:60 − 10:10 = 1:50.',3),
  q('cat-spt','How many edges does a tetrahedron have?',['6','4','8','12'],'6','A tetrahedron has 4 faces, 4 vertices, and 6 edges.',2),
  q('cat-spt','If the net of a shape has 6 squares of equal size, the 3D shape is:',['Cube','Cuboid','Prism','Pyramid'],'Cube','A net of 6 equal squares folds into a cube.',1),
  q('cat-spt','A solid cone is cut horizontally halfway up its height. The cross-section is a:',['Circle','Ellipse','Triangle','Rectangle'],'Circle','Any horizontal cut through a cone is a circle.',1),
  q('cat-spt','How many lines of symmetry does a regular hexagon have?',['6','3','4','8'],'6','A regular hexagon has 6 lines of symmetry.',1),
  q('cat-spt','A 4×4×4 cube is painted red on the outside and cut into 64 unit cubes. How many have NO painted faces?',['8','16','4','12'],'8','Interior cubes = 2×2×2 = 8',2),
  q('cat-spt','What is the minimum number of colours needed to colour a cube\'s faces so no two adjacent faces share a colour?',['3','2','4','6'],'3','A cube has opposite faces (non-adjacent); 3 colours suffice.',3),
  q('cat-spt','A rectangular box is 10×8×5 cm. What is its surface area?',['340 cm²','280 cm²','400 cm²','300 cm²'],'340 cm²','2(10×8+8×5+10×5)=2(80+40+50)=2(170)=340',2),
  q('cat-spt','Which solid has the most faces: cube, octahedron, dodecahedron, tetrahedron?',['Dodecahedron','Octahedron','Cube','Tetrahedron'],'Dodecahedron','Dodecahedron has 12 faces; octahedron 8; cube 6; tetrahedron 4.',1),
  q('cat-spt','If you look at a cube from directly above, you see:',['A square','A rectangle','A hexagon','A triangle'],'A square','Looking directly down at a cube shows a square face.',1),
  q('cat-spt','A shape has rotational symmetry of order 4. It looks the same after rotating by:',['90°','45°','180°','120°'],'90°','Order 4 means 4 identical positions in 360°; 360°/4=90°.',1),
  q('cat-spt','Which of these objects is NOT a polyhedron?',['Sphere','Cube','Pyramid','Prism'],'Sphere','A polyhedron has flat faces; a sphere has a curved surface.',1),

  // ─── ERROR CHECKING (20 questions) ────────────────────────────────────────
  q('cat-err','Find the error in the data entry: Name: JOHN BANDA, ID: ZM-0012, Amount: K1,250.00, Date: 2026-02-31',['Date: Feb has no 31st','Amount is wrong','ID format invalid','Name is misspelled'],'Date: Feb has no 31st','February never has 31 days.',1),
  q('cat-err','Spot the error: "The meeting is schedled for Monday."',['schedled → scheduled','meeting → Meeting','Monday → monday','no error'],'schedled → scheduled','Schedled is a typo; correct spelling is scheduled.',1),
  q('cat-err','Which code does NOT match the pattern ZM-NNNN (N=digit)?',['ZM-1234','ZM-0099','ZM-A012','ZM-5678'],'ZM-A012','A is not a digit; pattern requires 4 digits after ZM-.',1),
  q('cat-err','A spreadsheet shows: Jan=100, Feb=150, Mar=130, Total=390. Is the total correct?',['No: total should be 380','Yes: 390 is correct','No: total should be 400','No: total should be 370'],'No: total should be 380','100+150+130=380, not 390.',1),
  q('cat-err','Identify the inconsistency: Employee earns K5,000/month. Annual salary listed as K55,000.',['Annual should be K60,000','Annual is correct','Monthly should be K4,583','No inconsistency'],'Annual should be K60,000','K5,000×12=K60,000, not K55,000.',1),
  q('cat-err','Which phone number format is invalid for Zambia (must start with 09 or 07, 10 digits)?',['0978456321','0712345678','0812345678','0961234567'],'0812345678','Zambian numbers start with 09 or 07, not 08.',1),
  q('cat-err','Find the duplicate in this list: 101, 203, 305, 203, 407',['203','101','305','407'],'203','203 appears twice.',1),
  q('cat-err','A column of figures: 4,567 + 2,341 + 1,892 = 8,800. Is this correct?',['No: correct sum is 8,800','No: correct sum is 8,700','No: correct sum is 8,900','Yes, it is correct'],'No: correct sum is 8,800','4567+2341=6908+1892=8800. Actually correct! Answer: Yes, it is correct','4567+2341+1892=8800. The sum IS correct.',1),
  q('cat-err','Spot the error: "Recieve payment before dispatch of goods."',['Recieve → Receive','payment → Payment','dispatch → despatch','no error'],'Recieve → Receive','"I before E except after C": Receive, not Recieve.',1),
  q('cat-err','A date of birth is listed as 30/02/1995. What is wrong?',['February 30 does not exist','Year is too early','Day format wrong','Nothing is wrong'],'February 30 does not exist','February has at most 29 days.',1),
  q('cat-err','Which row has a calculation error?\nA: 12×5=60\nB: 14×6=84\nC: 13×7=91\nD: 15×8=115',['D','A','B','C'],'D','15×8=120, not 115.',1),
  q('cat-err','A bank code must be 8 alphanumeric characters. Which is invalid?',['AB12CD34','A1B2C3D4','ABCD1234','AB1234'],'AB1234','Only 6 characters; must be 8.',1),
  q('cat-err','Find the odd one out by format: K2,500.00 | K3,400.00 | K1200.00 | K5,600.00',['K1200.00','K2,500.00','K3,400.00','K5,600.00'],'K1200.00','Missing the thousands comma; should be K1,200.00.',1),
  q('cat-err','Which NRC format is valid (Zambia: NNNNNN/NN/N, N=digit)?',['123456/78/9','12345/78/9','123456/7/9','1234567/78/9'],'123456/78/9','6 digits, slash, 2 digits, slash, 1 digit.',1),
  q('cat-err','An invoice: Item=5, Unit Price=K200, Total=K950. Is the total correct?',['No: should be K1,000','Yes: K950 is correct','No: should be K900','No: should be K1,050'],'No: should be K1,000','5×K200=K1,000, not K950.',1),
  q('cat-err','Spot the inconsistency: "Customer DOB: 15/03/1990. Age: 34 years. Report Date: 2026-01-01."',['Age should be 35','Age is correct','DOB is wrong','Date format inconsistent'],'Age should be 35','By Jan 2026, a person born Mar 1990 has already had their 35th birthday... actually: Jan 2026 − Mar 1990 = 35 years 10 months → age=35.','Jan 2026 − Mar 1990: person turned 35 in Mar 2025. By Jan 2026 age=35.',2),
  q('cat-err','A sequence of codes: AA-001, AA-002, AA-004, AA-005. What is missing?',['AA-003','AA-006','AA-000','AA-007'],'AA-003','The sequence skips from 002 to 004; AA-003 is missing.',1),
  q('cat-err','Employee record: Start Date 2020-06-15, End Date 2019-12-31. What is wrong?',['End date is before start date','Start date format wrong','End date format wrong','Nothing is wrong'],'End date is before start date','Cannot end before starting.',1),
  q('cat-err','Which email address is invalid?',['user@domain.com','user.name@domain.co.zm','user@domain','user+tag@domain.org'],'user@domain','Missing a TLD (e.g. .com); user@domain is not a valid email.',1),
  q('cat-err','A tally shows: Mon=23, Tue=31, Wed=28, Thu=25, Fri=30. Weekly total given as 147. Correct?',['No: should be 137','No: should be 147','No: should be 140','Yes: 147 is correct'],'No: should be 137','23+31+28+25+30=137, not 147.',1),

  // ─── MECHANICAL REASONING (20 questions) ─────────────────────────────────
  q('cat-mec','If gear A (20 teeth) drives gear B (40 teeth), and A rotates at 100 RPM, what is B\'s RPM?',['50 RPM','200 RPM','100 RPM','25 RPM'],'50 RPM','Speed ratio is inverse of gear ratio: 100×20/40=50.',1),
  q('cat-mec','A lever has a fulcrum at its centre. A 10 kg weight is placed 2 m from the fulcrum on the left. To balance it, a weight on the right side 4 m from fulcrum must be:',['5 kg','10 kg','2.5 kg','8 kg'],'5 kg','Moments: 10×2=F×4 → F=5 kg.',1),
  q('cat-mec','Water flows through a pipe at 4 m/s. The pipe narrows to half its diameter. New flow speed:',['16 m/s','8 m/s','2 m/s','4 m/s'],'16 m/s','Area ∝ d²; half diameter = ¼ area; continuity: speed×4=16 m/s.',2),
  q('cat-mec','A pulley system has mechanical advantage of 3. A force of 50 N can lift:',['150 N','50 N','100 N','200 N'],'150 N','MA=Load/Effort: Load=3×50=150 N.',1),
  q('cat-mec','Which simple machine is a ramp?',['Inclined plane','Wedge','Lever','Pulley'],'Inclined plane','A ramp is an inclined plane.',1),
  q('cat-mec','If a spring stretches 5 cm under 10 N force, how much will it stretch under 25 N (Hooke\'s Law)?',['12.5 cm','15 cm','10 cm','20 cm'],'12.5 cm','k=10/5=2 N/cm; x=25/2=12.5 cm.',1),
  q('cat-mec','A wheel and axle: wheel radius=30 cm, axle radius=5 cm. Mechanical advantage?',['6','5','3','10'],'6','MA=R_wheel/R_axle=30/5=6.',1),
  q('cat-mec','Which type of screw converts rotary motion to linear motion?',['Lead screw','Wood screw','Bolt','Lag screw'],'Lead screw','A lead screw (or ball screw) converts rotation to linear motion.',2),
  q('cat-mec','A object is on an inclined plane at 30°. The component of gravity acting along the plane is:',['mg sin 30°','mg cos 30°','mg tan 30°','mg'],'mg sin 30°','The component along the slope = mg×sin(θ).',2),
  q('cat-mec','Two gears: if gear A rotates clockwise, gear B (meshed directly) rotates:',['Counter-clockwise','Clockwise','Does not rotate','Depends on size'],'Counter-clockwise','Meshed gears rotate in opposite directions.',1),
  q('cat-mec','A hydraulic jack: small piston area=10 cm², large piston area=100 cm². Force applied=50 N. Output force?',['500 N','50 N','5 N','5,000 N'],'500 N','Pascal\'s principle: F_out=F_in×(A_out/A_in)=50×10=500 N.',2),
  q('cat-mec','Which material is the best electrical conductor?',['Copper','Iron','Aluminium','Steel'],'Copper','Copper has the highest electrical conductivity among common metals.',1),
  q('cat-mec','A bicycle uses a small chain gear (16 teeth) driving a large gear (32 teeth). For every pedal revolution, the wheel turns:',['0.5 times','2 times','1 time','4 times'],'0.5 times','16/32=0.5 wheel revolutions per pedal revolution.',2),
  q('cat-mec','Which type of beam is supported at one end only?',['Cantilever','Simply supported','Continuous','Fixed-fixed'],'Cantilever','A cantilever beam is fixed at one end and free at the other.',1),
  q('cat-mec','A car engine converts chemical energy into:',['Mechanical energy','Electrical energy','Thermal energy only','Light energy'],'Mechanical energy','Combustion → heat → mechanical (kinetic) energy to move the car.',1),
  q('cat-mec','Pressure = Force / Area. A force of 200 N acts on 0.5 m². The pressure is:',['400 Pa','100 Pa','200 Pa','1000 Pa'],'400 Pa','P=200/0.5=400 Pa.',1),
  q('cat-mec','A transformer has 100 turns on primary and 500 turns on secondary. Input voltage is 240 V. Output voltage?',['1,200 V','48 V','240 V','600 V'],'1,200 V','V_s/V_p = N_s/N_p; V_s=240×500/100=1200 V.',2),
  q('cat-mec','Which type of joint allows rotation in all directions?',['Ball-and-socket','Hinge','Pivot','Gliding'],'Ball-and-socket','Ball-and-socket joints (like hip/shoulder) allow multi-directional rotation.',1),
  q('cat-mec','Newton\'s Third Law states:',['For every action there is an equal and opposite reaction','Force equals mass times acceleration','An object at rest stays at rest','Energy cannot be created or destroyed'],'For every action there is an equal and opposite reaction','Newton\'s Third Law of Motion.',1),
  q('cat-mec','An electric motor consumes 1,000 W and outputs 800 W of mechanical power. Its efficiency is:',['80%','90%','75%','85%'],'80%','Efficiency=Output/Input×100=800/1000×100=80%.',1),

  // ─── SITUATIONAL JUDGEMENT (20 questions) ─────────────────────────────────
  q('cat-sit','A colleague is consistently late with reports, affecting your team. What should you do first?',['Speak to the colleague privately','Report immediately to management','Complain to other colleagues','Do the work yourself'],'Speak to the colleague privately','Address issues directly and respectfully before escalating.',1),
  q('cat-sit','You discover a minor error in a report already sent to a client. You should:',['Inform your manager and correct it promptly','Wait to see if the client notices','Deny the error if asked','Ignore it; it is minor'],'Inform your manager and correct it promptly','Transparency and prompt correction protect trust.',1),
  q('cat-sit','A client is angry about a delayed order and is being rude. You should:',['Stay calm, apologise, and find a solution','Match their anger to show seriousness','Transfer immediately without explanation','Hang up and report them'],'Stay calm, apologise, and find a solution','Professional de-escalation and problem-solving.',1),
  q('cat-sit','You are given two urgent tasks by different managers. You should:',['Clarify priorities with both managers','Do the task from the senior manager only','Do the easier task first','Ask a colleague to do one'],'Clarify priorities with both managers','Communicate to avoid conflict and ensure the right task is prioritised.',1),
  q('cat-sit','You notice a colleague may be falsifying expense claims. You should:',['Report your concern through proper channels','Confront them directly and accusingly','Tell other colleagues','Ignore it; it\'s not your concern'],'Report your concern through proper channels','Ethical breaches must be reported appropriately.',2),
  q('cat-sit','Your manager asks you to do something you believe is unethical. You should:',['Express concern and seek clarification','Do it without question','Refuse immediately and loudly','Quit on the spot'],'Express concern and seek clarification','Address concerns professionally before escalating.',2),
  q('cat-sit','You are in a meeting and someone presents incorrect data. You should:',['Politely raise the discrepancy with evidence','Stay silent to avoid embarrassment','Interrupt loudly to correct them','Tell others after the meeting'],'Politely raise the discrepancy with evidence','Accurate information is critical; address it professionally.',2),
  q('cat-sit','A new team member is struggling. The most effective response is:',['Offer guidance and check in regularly','Let them figure it out alone','Report their struggle to management immediately','Take over all their tasks'],'Offer guidance and check in regularly','Supportive mentoring improves team performance.',1),
  q('cat-sit','You make a significant mistake on a project. The best response is:',['Acknowledge it, learn from it, and fix it','Blame the circumstances','Hope no one notices','Blame a team member'],'Acknowledge it, learn from it, and fix it','Accountability and corrective action are professional virtues.',1),
  q('cat-sit','A client requests a service outside your authority to approve. You should:',['Escalate to someone with authority','Agree and sort it out later','Decline without explanation','Refer them elsewhere without help'],'Escalate to someone with authority','Know your limits and involve the right people.',1),
  q('cat-sit','You overhear two colleagues speaking negatively about another team member. You should:',['Encourage them to address it constructively or not engage','Join in the conversation','Report them immediately','Confront the subject of the conversation'],'Encourage them to address it constructively or not engage','Discourage toxic behaviour without overreacting.',2),
  q('cat-sit','You are overwhelmed with work and cannot meet a deadline. You should:',['Communicate early and negotiate the deadline','Say nothing and deliver late','Stay up all night and deliver poor work','Blame workload in a meeting'],'Communicate early and negotiate the deadline','Proactive communication prevents bigger problems.',1),
  q('cat-sit','During a performance review, your manager gives unfair criticism. You should:',['Calmly provide evidence of your performance','Become defensive and argue','Accept all feedback without question','Complain to HR immediately'],'Calmly provide evidence of your performance','Evidence-based, professional response to unfair feedback.',2),
  q('cat-sit','A customer requests a refund against company policy. You should:',['Explain the policy empathetically and offer alternatives','Strictly enforce policy with no discussion','Override the policy to please the customer','Ignore the request'],'Explain the policy empathetically and offer alternatives','Balance policy adherence with customer care.',2),
  q('cat-sit','You are asked to work overtime without additional pay. You should:',['Discuss the request respectfully with your manager','Refuse immediately','Work overtime without comment','File a formal complaint straight away'],'Discuss the request respectfully with your manager','Open dialogue is the first step.',1),
  q('cat-sit','Your team disagrees on an approach to a project. As a team member, you should:',['Facilitate open discussion to reach consensus','Insist on your preferred approach','Go with the majority without raising concerns','Let the manager decide without team input'],'Facilitate open discussion to reach consensus','Collaborative decision-making leads to better outcomes.',2),
  q('cat-sit','A colleague confides that they are struggling with personal issues affecting work. You should:',['Listen, show empathy, and suggest support resources','Tell your manager immediately','Treat them differently at work','Share this with other colleagues'],'Listen, show empathy, and suggest support resources','Supportive, confidential, and constructive response.',1),
  q('cat-sit','You receive a task with unclear instructions. You should:',['Seek clarification before starting','Make assumptions and begin','Ask a colleague to do it instead','Wait for the manager to follow up'],'Seek clarification before starting','Clarifying ambiguity prevents wasted effort.',1),
  q('cat-sit','You notice a safety hazard in the workplace. You should:',['Report it immediately to the responsible person','Report it next week if it persists','Wait for others to notice','Avoid the area only'],'Report it immediately to the responsible person','Safety hazards require immediate action.',1),
  q('cat-sit','Your organisation adopts a new system you find difficult. You should:',['Seek training, practice, and ask for help','Resist the change and use the old system','Complain publicly about the change','Accept it passively without trying to learn'],'Seek training, practice, and ask for help','Proactive adaptation to change is professional.',1),

  // ─── INDUCTIVE REASONING (15 questions) ──────────────────────────────────
  q('cat-ind','All swans observed so far have been white. Therefore:',['The next swan is likely white','All swans are definitely white','No swan can be black','Swans do not exist'],'The next swan is likely white','Inductive reasoning yields probable, not certain, conclusions.',2),
  q('cat-ind','Every Monday for the past year, the team meeting was cancelled. Next Monday\'s meeting will likely be:',['Cancelled','Held as normal','Rescheduled to Tuesday','Impossible to predict'],'Cancelled','Past pattern strongly suggests continuation.',1),
  q('cat-ind','A pattern: 2, 4, 8, 16. The rule is:',['Multiply by 2','Add 2','Square the previous','Add 4'],'Multiply by 2','Each term doubles the previous.',1),
  q('cat-ind','Every product tested from Batch A has been defective. Batch A likely:',['Has a manufacturing fault','Is randomly defective','Is fine; the testers are wrong','Has only defective products only by chance'],'Has a manufacturing fault','Consistent defects suggest a systematic cause.',2),
  q('cat-ind','Identify the rule: 3, 6, 11, 18, 27, ?',['38','36','40','33'],'38','Differences: 3,5,7,9,11 → next diff=11 → 27+11=38.',2),
  q('cat-ind','A researcher notices that cities with more libraries have higher literacy rates. She concludes:',['Libraries and literacy are correlated','Libraries cause literacy','Literacy causes libraries','There is no relationship'],'Libraries and literacy are correlated','Inductive observation shows correlation, not causation.',2),
  q('cat-ind','Identify the pattern: J, F, M, A, M, J, J, A, ?',['S','O','N','D'],'S','Months: January through September → S (September).',1),
  q('cat-ind','Which generalisation is best supported? (3 out of 3 sampled red balls from a bag)',['The bag probably contains mostly red balls','The bag contains only red balls','The bag contains no other colours','Nothing can be inferred'],'The bag probably contains mostly red balls','A small sample gives probable but not certain conclusions.',2),
  q('cat-ind','Complete the series: 1, 8, 27, 64, ?',['125','100','144','216'],'125','Cubes: 5³=125.',1),
  q('cat-ind','A child touches a hot stove twice and is burned both times. She concludes stoves are hot. This is:',['Inductive reasoning','Deductive reasoning','Abductive reasoning','No reasoning'],'Inductive reasoning','Drawing a general rule from specific observations.',1),
  q('cat-ind','Every employee who attended the training program received a promotion. Jane attended. What can be induced?',['Jane is likely to be promoted','Jane will definitely be promoted','Jane will not be promoted','No conclusion possible'],'Jane is likely to be promoted','Inductive: likely but not certain.',1),
  q('cat-ind','Pattern: Monday sales = K5,000, Tuesday = K4,800, Wednesday = K4,600. Thursday sales will likely be:',['K4,400','K4,000','K5,200','K4,600'],'K4,400','Decreasing by K200 each day.',1),
  q('cat-ind','A scientist observes that metal expands when heated 100 times. She concludes metals expand when heated. This is:',['Inductive','Deductive','Hypothetical','Circular'],'Inductive','Specific observations → general principle.',1),
  q('cat-ind','Rule: output = input² − 1. Input=5, output=?',['24','25','26','23'],'24','5²−1=24.',1),
  q('cat-ind','From the pattern 10, 9, 7, 4, 0, the next number is:',['−5','−4','−3','−6'],'−5','Differences: −1,−2,−3,−4,−5 → 0+(−5)=−5.',2),

  // ─── DEDUCTIVE REASONING (15 questions) ──────────────────────────────────
  q('cat-ded','All mammals are warm-blooded. Whales are mammals. Therefore:',['Whales are warm-blooded','Whales are cold-blooded','Some mammals are not warm-blooded','Whales are fish'],'Whales are warm-blooded','Valid syllogism: All A are B; C is A; → C is B.',1),
  q('cat-ded','If it is a public holiday, banks are closed. Banks are open. Therefore:',['It is not a public holiday','It is a public holiday','Banks are sometimes closed','Holidays are rare'],'It is not a public holiday','Modus tollens: P→Q, ¬Q → ¬P.',1),
  q('cat-ded','All prime numbers greater than 2 are odd. 17 is a prime number greater than 2. Therefore:',['17 is odd','17 is even','17 is not prime','17 is divisible by 2'],'17 is odd','Direct application of the rule.',1),
  q('cat-ded','No reptile is warm-blooded. All snakes are reptiles. Therefore:',['No snake is warm-blooded','Some snakes are warm-blooded','All warm-blooded animals are reptiles','Reptiles can be warm-blooded'],'No snake is warm-blooded','No A is B; all C are A → no C is B.',1),
  q('cat-ded','Given: If A then B. If B then C. A is true. Which is true?',['Both B and C','Only B','Only C','Neither'],'Both B and C','A→B (true), B→C → both B and C are true.',1),
  q('cat-ded','Some A are B. No B are C. Therefore:',['Some A are not C','All A are C','No A are C','Some A are C'],'Some A are not C','Those A that are also B cannot be C.',2),
  q('cat-ded','All squares have 4 sides. This shape has 4 sides. Therefore:',['This shape may be a square','This shape is definitely a square','This shape is not a square','4-sided shapes do not exist'],'This shape may be a square','Having 4 sides is necessary but not sufficient to be a square.',2),
  q('cat-ded','Rule: Employees with 5+ years get a bonus. Sam has worked for 7 years. Sam:',['Gets a bonus','Does not get a bonus','May or may not get a bonus','The rule doesn\'t apply'],'Gets a bonus','7≥5 → Sam qualifies.',1),
  q('cat-ded','Only members can vote. Jane voted. Therefore:',['Jane is a member','Jane is not a member','Non-members sometimes vote','Jane may or may not be a member'],'Jane is a member','Only members can vote → anyone who voted is a member.',1),
  q('cat-ded','All integers divisible by 6 are divisible by 3. 42 is divisible by 6. Therefore:',['42 is divisible by 3','42 is not divisible by 3','3 is divisible by 42','42 is prime'],'42 is divisible by 3','Direct application; 42÷3=14.',1),
  q('cat-ded','P: All registered vehicles have insurance. Q: This vehicle has no insurance. Conclusion:',['This vehicle is not registered','This vehicle is registered','Insurance is optional','Vehicles need not be registered'],'This vehicle is not registered','Modus tollens.',1),
  q('cat-ded','If a number is even, it is divisible by 2. 36 is even. Therefore:',['36 is divisible by 2','36 is odd','36 is prime','36 is not divisible by 2'],'36 is divisible by 2','Even → divisible by 2.',1),
  q('cat-ded','Rule: Late submissions are penalised. Grace submitted on time. Therefore:',['Grace is not penalised','Grace is penalised','Grace may be penalised','We cannot tell'],'Grace is not penalised','Only late submissions are penalised; Grace is on time → no penalty.',1),
  q('cat-ded','All students who pass the exam get a certificate. Tom did not get a certificate. Therefore:',['Tom did not pass','Tom passed','Tom did not take the exam','Certificates are optional'],'Tom did not pass','Contrapositive: ¬certificate → ¬pass.',1),
  q('cat-ded','Every multiple of 4 is even. 28 is a multiple of 4. Therefore:',['28 is even','28 is odd','4 is a multiple of 28','28 is prime'],'28 is even','Multiples of 4 are even; 28÷4=7.',1),

  // ─── DIAGRAMMATIC REASONING (15 questions) ───────────────────────────────
  q('cat-dia','A flowchart: START → Input number → Is number > 0? → YES: Output "Positive" | NO: Output "Non-positive" → END. Input = −3. Output:',['Non-positive','Positive','Zero','Error'],'Non-positive','−3 is not >0 → Non-positive.',1),
  q('cat-dia','A Venn diagram shows circle A = Dogs, circle B = Animals that swim. The overlap represents:',['Dogs that can swim','All dogs','All swimming animals','Non-swimming dogs'],'Dogs that can swim','The intersection of two sets.',1),
  q('cat-dia','A process diagram shows 4 steps in a loop. If each loop takes 3 minutes and you need 5 loops, total time:',['15 minutes','12 minutes','20 minutes','9 minutes'],'15 minutes','5×3=15.',1),
  q('cat-dia','A decision tree: if rain → take umbrella; if no rain → no umbrella. Today: rain. Action:',['Take umbrella','No umbrella','Cannot decide','Check forecast'],'Take umbrella','Rain condition → take umbrella.',1),
  q('cat-dia','A state machine has states A, B, C. A→B on input 0; A→C on input 1; B→A on input 0. Starting at A with inputs 1,0: final state?',['A','B','C','D'],'A','A→C (on 1); C→? — if not defined, stays C... but question says B→A on 0. A with input 1 → C; C with input 0: not defined in question. Best: if C has no rule for 0, stays C. Checking options: likely A is intended as A→C→A if C→A on 0.','Assuming C→A on 0: A→C(input1)→A(input0) = A.',3),
  q('cat-dia','A flowchart multiplies input by 2 then subtracts 3. Input=7. Output:',['11','14','10','17'],'11','7×2=14−3=11.',1),
  q('cat-dia','A bar chart shows sales: Jan=200, Feb=250, Mar=180. Which month had the highest sales?',['February','January','March','All equal'],'February','250 > 200 > 180.',1),
  q('cat-dia','A logic gate diagram: AND gate with inputs A=1, B=0. Output:',['0','1','Undefined','Depends'],'0','AND gate: output=1 only if both inputs=1.',1),
  q('cat-dia','A pie chart has 4 equal sectors. Each sector represents what percentage?',['25%','20%','30%','10%'],'25%','360°÷4=90° each = 25%.',1),
  q('cat-dia','A flowchart loop counts from 1 to 5, adding 1 each time. How many times does it loop?',['5','4','6','3'],'5','Counts 1,2,3,4,5 = 5 iterations.',1),
  q('cat-dia','An OR gate has inputs A=0, B=0. Output:',['0','1','Undefined','Both'],'0','OR gate: output=1 if at least one input=1; both 0 → output=0.',1),
  q('cat-dia','A network diagram shows critical path A→C→E = 15 days. Path A→B→D→E = 12 days. Project duration:',['15 days','12 days','27 days','10 days'],'15 days','Critical path (longest) determines project duration.',2),
  q('cat-dia','A flowchart: input x → if x>10 → output x−10, else output x+10. Input=8. Output:',['18','8','-2','2'],'18','8 is not >10 → 8+10=18.',1),
  q('cat-dia','A NOT gate has input A=1. Output:',['0','1','Undefined','Same as input'],'0','NOT gate inverts: NOT 1 = 0.',1),
  q('cat-dia','A tree diagram shows 2 possible outcomes at each of 3 stages. Total paths:',['8','6','4','12'],'8','2³=8.',1),

  // ─── READING COMPREHENSION (15 questions) ─────────────────────────────────
  q('cat-rc','Passage: "Zambia declared independence from British rule on 24 October 1964. Kenneth Kaunda became the first president." When did Zambia become independent?',['24 October 1964','1 January 1964','24 October 1954','12 March 1966'],'24 October 1964','Directly stated in the passage.',1),
  q('cat-rc','Passage: "Regular exercise reduces the risk of heart disease, diabetes, and obesity." Which claim is directly supported?',['Exercise reduces obesity risk','Exercise cures all diseases','Exercise is unnecessary','Diet alone prevents disease'],'Exercise reduces obesity risk','Explicitly stated in the passage.',1),
  q('cat-rc','Passage: "The report was comprehensive but lacked actionable recommendations." What was missing?',['Actionable recommendations','Data analysis','A summary','References'],'Actionable recommendations','Directly stated.',1),
  q('cat-rc','Passage: "All participants were volunteers. None were paid." What can be inferred?',['Participation was not compulsory','Participation was compulsory','Participants were staff members','Some were paid'],'Participation was not compulsory','Volunteers choose to participate; hence not compulsory.',1),
  q('cat-rc','Passage: "Despite economic challenges, the company posted a K2 million profit." The tone is:',['Positive despite adversity','Purely negative','Alarming','Neutral and statistical'],'Positive despite adversity','"Despite challenges" but profit = positive outcome.',1),
  q('cat-rc','Passage: "Studies show that 70% of employees feel disengaged at work." The word "disengaged" most likely means:',['Not motivated or involved','Very productive','Absent from work','Recently resigned'],'Not motivated or involved','Disengaged = not actively involved or enthusiastic.',1),
  q('cat-rc','Passage: "The policy applies to all staff, including contractors." Does it apply to contractors?',['Yes','No','Only sometimes','The passage is unclear'],'Yes','Explicitly stated: "including contractors".',1),
  q('cat-rc','Passage: "She reluctantly agreed to chair the committee." Her attitude was:',['Unwilling but compliant','Enthusiastic','Opposed and refused','Indifferent'],'Unwilling but compliant','"Reluctantly" = unwillingly; "agreed" = compliant.',1),
  q('cat-rc','Passage: "The new system is faster, cheaper, and easier to use than its predecessor." The old system was:',['Slower, more expensive, and harder to use','Equally efficient','Newer','Not mentioned'],'Slower, more expensive, and harder to use','The new system is better in all three ways → the old was worse.',1),
  q('cat-rc','Passage: "The author argues that urbanisation, not industrialisation, is the primary driver of inequality." What does the author claim?',['Urbanisation drives inequality more than industrialisation','Industrialisation causes inequality','Both factors are equal','Neither factor matters'],'Urbanisation drives inequality more than industrialisation','Directly stated as the author\'s argument.',1),
  q('cat-rc','Passage: "He spoke at length but said very little of substance." This means:',['He was verbose but not informative','He was brief and precise','He was informative but quiet','He refused to speak'],'He was verbose but not informative','Spoke at length = verbose; said little of substance = uninformative.',1),
  q('cat-rc','Passage: "The trial concluded with a unanimous verdict." How many jurors disagreed?',['None','All','Half','One'],'None','Unanimous = all agreed; none disagreed.',1),
  q('cat-rc','Passage: "Failure to comply will result in suspension." What is the consequence of non-compliance?',['Suspension','A fine','Dismissal','A warning'],'Suspension','Directly stated.',1),
  q('cat-rc','Passage: "The data suggests a correlation, not causation, between the variables." A valid conclusion is:',['The variables may be related but one does not cause the other','One variable definitely causes the other','The variables are unrelated','Causation was proven'],'The variables may be related but one does not cause the other','Correlation ≠ causation — directly supported.',1),
  q('cat-rc','Passage: "This approach is innovative but untested." The author implies:',['The approach is new and its effectiveness is unproven','The approach has been tested thoroughly','The approach has failed','Innovation is always bad'],'The approach is new and its effectiveness is unproven','"Innovative" = new; "untested" = unproven effectiveness.',1),

  // ─── QUANTITATIVE APTITUDE (20 questions) ────────────────────────────────
  q('cat-qa','What is the value of (16)^(3/4)?',['8','4','12','6'],'8','16^(1/4)=2; 2³=8.',2),
  q('cat-qa','A man invests K10,000 at 12% p.a. compounded quarterly. Effective annual rate (approx)?',['12.55%','12%','12.36%','13%'],'12.55%','EAR=(1+0.12/4)⁴−1=(1.03)⁴−1≈12.55%.',3),
  q('cat-qa','A boat goes 24 km downstream in 2 hours and 16 km upstream in 4 hours. Speed of stream:',['2 km/h','4 km/h','3 km/h','1 km/h'],'2 km/h','Downstream=12, upstream=4; stream=(12−4)/2=4... (12+4)/2=8 boat, (12−4)/2=4 stream','D=12 km/h, U=4 km/h; stream=(12−4)/2=4 km/h',3),
  q('cat-qa','Find the value of log₂(64).',['6','8','5','4'],'6','2⁶=64.',1),
  q('cat-qa','If A can do a job in 10 days and B in 15 days, how many days together?',['6','5','8','4'],'6','1/10+1/15=5/30=1/6 → 6 days.',1),
  q('cat-qa','A train 200 m long passes a pole in 20 seconds. Its speed in km/h?',['36','40','30','45'],'36','Speed=200/20=10 m/s=36 km/h.',1),
  q('cat-qa','In how many ways can 4 people be arranged in a line?',['24','12','48','16'],'24','4! = 24.',1),
  q('cat-qa','From 6 men and 4 women, a committee of 3 men and 2 women is chosen. Ways:',['120','60','240','180'],'120','C(6,3)×C(4,2)=20×6=120.',2),
  q('cat-qa','What is the probability of getting at least one head in 3 coin flips?',['7/8','1/2','3/4','1/4'],'7/8','1−P(no heads)=1−(1/2)³=7/8.',2),
  q('cat-qa','The difference between compound interest (yearly) and simple interest on K2,000 at 10% for 2 years:',['K20','K40','K10','K30'],'K20','SI=400; CI=2000(1.1²−1)=420; diff=20.',2),
  q('cat-qa','Find the mode of: 4, 7, 4, 9, 4, 7, 2, 7, 4.',['4','7','2','9'],'4','4 appears 4 times, 7 appears 3 times.',1),
  q('cat-qa','Simplify: (x²−4)/(x−2)',['x+2','x−2','x²+2','2x'],'x+2','(x+2)(x−2)/(x−2)=x+2.',1),
  q('cat-qa','A bag has 5 red and 3 blue balls. Probability of drawing 2 red balls without replacement?',['5/14','5/16','1/4','3/8'],'5/14','(5/8)×(4/7)=20/56=5/14.',2),
  q('cat-qa','What is the standard deviation of: 2, 4, 4, 4, 5, 5, 7, 9?',['2','1','3','4'],'2','Mean=5; variance=[(9+1+1+1+0+0+4+16)/8]=32/8=4; SD=2.',3),
  q('cat-qa','Express 0.333... as a fraction.',['1/3','1/4','3/9','2/6'],'1/3','0.333... = 1/3.',1),
  q('cat-qa','The sum of an arithmetic series: first term=3, last term=99, n=17 terms.',['867','850','900','816'],'867','S=n/2×(a+l)=17/2×102=867.',2),
  q('cat-qa','Factorise: x² + 5x + 6',['(x+2)(x+3)','(x+1)(x+6)','(x−2)(x−3)','(x+6)(x−1)'],'(x+2)(x+3)','2+3=5, 2×3=6.',1),
  q('cat-qa','A shopkeeper mixes 20 kg at K30/kg with 30 kg at K40/kg. Average cost per kg?',['K36','K35','K37','K34'],'K36','(20×30+30×40)/50=(600+1200)/50=1800/50=36.',1),
  q('cat-qa','If P(A)=0.4 and P(B)=0.3 and A,B independent, find P(A∩B).',['0.12','0.7','0.58','0.1'],'0.12','P(A∩B)=P(A)×P(B)=0.4×0.3=0.12.',1),
  q('cat-qa','Find the nth term of 5, 8, 11, 14, ...',['3n+2','2n+3','3n+5','n+4'],'3n+2','a=5, d=3; Tn=5+(n−1)3=3n+2.',1),

  // ─── CRITICAL THINKING (15 questions) ────────────────────────────────────
  q('cat-ct','An advertisement claims: "9 out of 10 dentists recommend our toothpaste." What is a valid concern?',['What did the 10th dentist say, and how were dentists selected?','The claim is definitely true','All toothpastes are equally good','Dentists are not qualified to recommend toothpaste'],'What did the 10th dentist say, and how were dentists selected?','Sample bias and selection method affect the validity of the claim.',2),
  q('cat-ct','Argument: "Sales are up 50% this quarter. Our new marketing campaign must be working." The weakness is:',['Other factors may explain the increase','Sales should have increased more','Marketing is not important','50% is not significant'],'Other factors may explain the increase','Correlation does not imply causation; other variables could explain the increase.',2),
  q('cat-ct','What is the main assumption in: "People who eat breakfast perform better at work. Offering breakfast will boost employee performance."?',['Eating breakfast causes better performance','Breakfast is expensive','Performance is not important','Employees dislike breakfast'],'Eating breakfast causes better performance','The argument assumes correlation = causation.',2),
  q('cat-ct','Identify the strongest counter-argument to: "We should ban all cars to reduce pollution."',['Alternative vehicles can reduce pollution without banning cars','Cars are essential','Pollution is not serious','Banning things never works'],'Alternative vehicles can reduce pollution without banning cars','A targeted, practical alternative addresses the goal without an extreme measure.',2),
  q('cat-ct','Which statement is a fact rather than an opinion?',['Zambia gained independence in 1964','Zambia is the best country in Africa','Zambia\'s culture is more vibrant than Kenya\'s','Zambia should join a federation'],'Zambia gained independence in 1964','This is a verifiable historical fact.',1),
  q('cat-ct','Evaluate: "Since crime rates fell after the curfew, the curfew caused the reduction." The flaw is:',['Post hoc fallacy — correlation mistaken for causation','The data is wrong','Curfews always increase crime','The conclusion is valid'],'Post hoc fallacy — correlation mistaken for causation','Post hoc ergo propter hoc: happening after ≠ caused by.',2),
  q('cat-ct','Which question is most useful for critically evaluating a research study?',['Who funded the research?','Is the title attractive?','Was it published recently?','Does it support my view?'],'Who funded the research?','Funding sources can introduce bias; this is a key critical evaluation question.',2),
  q('cat-ct','An argument has a valid form but a false premise. The conclusion is:',['May be true or false','Definitely true','Definitely false','Irrelevant'],'May be true or false','Valid form means if premises were true, conclusion follows. False premise makes conclusion uncertain.',3),
  q('cat-ct',' "If we allow gay marriage, next people will want to marry animals." This is an example of:',['Slippery slope fallacy','Ad hominem','Straw man','Appeal to authority'],'Slippery slope fallacy','Assumes one step inevitably leads to extreme, unrelated consequences.',2),
  q('cat-ct','What does it mean to "steelman" an argument?',['Present the strongest version of the opposing view','Defeat every opposing argument','Repeat your own argument forcefully','Use statistics to support your view'],'Present the strongest version of the opposing view','The opposite of a straw man; steelmanning strengthens opposing arguments.',2),
  q('cat-ct','A study reports "X causes Y" with p < 0.05. A critical reader should note:',['Statistical significance does not guarantee practical significance or causation','The finding is definitely correct','p < 0.05 means 95% certainty of causation','The study is invalid'],'Statistical significance does not guarantee practical significance or causation','p-values indicate likelihood under null hypothesis, not effect size or causation.',3),
  q('cat-ct','Which source is likely MOST reliable for medical advice?',['A peer-reviewed journal article','A celebrity health blog','A social media post','An anecdote from a friend'],'A peer-reviewed journal article','Peer-reviewed research undergoes expert scrutiny.',1),
  q('cat-ct','Argument: "Everyone is moving to solar power, so you should too." This is an example of:',['Bandwagon appeal','Appeal to authority','Slippery slope','False dilemma'],'Bandwagon appeal','Arguing something is right because many people do it.',1),
  q('cat-ct','What is the difference between a claim and evidence?',['A claim is an assertion; evidence supports or refutes it','They are the same thing','Evidence is an opinion','Claims are always true'],'A claim is an assertion; evidence supports or refutes it','Fundamental distinction in critical thinking.',1),
  q('cat-ct','The conclusion "All politicians are corrupt" based on three corrupt politicians is an example of:',['Hasty generalisation','Deductive reasoning','Valid induction','Modus ponens'],'Hasty generalisation','Drawing a broad conclusion from too few examples.',2),

  // ─── PERSONALITY & BEHAVIOURAL (15 questions) ────────────────────────────
  q('cat-pb','When given a complex task with no clear instructions, you typically:',['Break it into smaller steps and start','Wait for complete instructions','Ask someone else to do it','Feel overwhelmed and avoid it'],'Break it into smaller steps and start','Self-starters demonstrate initiative and problem-solving.',1),
  q('cat-pb','Which best describes how you handle criticism?',['Use it to improve your performance','Feel personally attacked','Ignore it','Become defensive immediately'],'Use it to improve your performance','Openness to feedback is a sign of emotional maturity.',1),
  q('cat-pb','When working in a team with a difficult member, you:',['Communicate directly but respectfully','Ignore and work around them','Complain to the manager immediately','Confront them aggressively'],'Communicate directly but respectfully','Constructive communication resolves conflict.',1),
  q('cat-pb','You prefer to work:',['Flexibly, adapting to what the situation needs','Strictly alone','Only in groups','With constant supervision'],'Flexibly, adapting to what the situation needs','Adaptability is a valued professional trait.',1),
  q('cat-pb','How do you respond to a very tight deadline?',['Prioritise, focus, and communicate if unrealistic','Panic and do poor work','Ignore the deadline','Ask for an extension immediately'],'Prioritise, focus, and communicate if unrealistic','Effective deadline management balances action and communication.',1),
  q('cat-pb','When you disagree with your manager\'s decision, you:',['Respectfully express your view and then support the decision','Disobey the decision','Complain to colleagues','Resign immediately'],'Respectfully express your view and then support the decision','Professional disagreement follows the chain of command.',1),
  q('cat-pb','You take on a new responsibility you have not done before. Your reaction is:',['See it as a learning opportunity','Refuse politely','Feel incapable','Ask someone else to take it'],'See it as a learning opportunity','Growth mindset: new responsibilities are development opportunities.',1),
  q('cat-pb','Which work style do you most identify with?',['Organised and goal-oriented','Spontaneous with no planning','Reactive only to urgent tasks','Dependent on others for direction'],'Organised and goal-oriented','Organisation and goal-orientation are strong predictors of performance.',1),
  q('cat-pb','When you receive a complex problem to solve, your first step is to:',['Gather all relevant information','Jump to the first solution you think of','Ask someone else to solve it','Wait for the problem to resolve itself'],'Gather all relevant information','Effective problem-solving begins with understanding the problem fully.',1),
  q('cat-pb','How do you handle multiple competing priorities?',['Create a priority list and tackle the most critical first','Do tasks randomly','Focus on the easiest tasks','Do all tasks at once poorly'],'Create a priority list and tackle the most critical first','Structured prioritisation is key to managing workload.',1),
  q('cat-pb','You make a significant error at work. Your first reaction is:',['Acknowledge the mistake and find a solution','Blame others','Hide the mistake','Worry without acting'],'Acknowledge the mistake and find a solution','Accountability + corrective action = professional maturity.',1),
  q('cat-pb','In high-pressure situations, you tend to:',['Stay calm and focus on what can be controlled','Become anxious and unproductive','Shut down completely','Overreact emotionally'],'Stay calm and focus on what can be controlled','Emotional regulation under pressure is a critical competency.',1),
  q('cat-pb','When given feedback you disagree with, you:',['Listen fully, ask clarifying questions, then reflect','Immediately argue your case','Dismiss it entirely','Feel deeply upset and distracted'],'Listen fully, ask clarifying questions, then reflect','Active listening and reflection before responding shows emotional intelligence.',2),
  q('cat-pb','You notice a colleague is struggling with their workload. You:',['Offer help if you have capacity','Ignore it','Tell the manager without speaking to them first','Take over all their work uninvited'],'Offer help if you have capacity','Collaborative support strengthens team performance.',1),
  q('cat-pb','Which describes your preferred approach to change at work?',['Embrace change and adapt quickly','Resist all change','Accept change only when forced','Ignore changes and work as before'],'Embrace change and adapt quickly','Adaptability and change readiness are increasingly valued in modern workplaces.',1),
];

async function main() {
  console.log(`Seeding ${QUESTIONS.length} questions across 15 categories...`);
  
  // Upsert categories
  for (const cat of CATEGORIES) {
    await p.category.upsert({
      where: { id: cat.id },
      update: { name: cat.name, description: cat.desc, slug: cat.id.replace('cat-','') },
      create: { id: cat.id, name: cat.name, description: cat.desc, slug: cat.id.replace('cat-','') },
    });
  }
  console.log('✅ 15 categories upserted');

  // Clear existing questions
  await p.question.deleteMany({});
  console.log('🗑  Cleared existing questions');

  // Insert all questions
  let count = 0;
  for (const q of QUESTIONS) {
    await p.question.create({ data: q });
    count++;
    if (count % 50 === 0) console.log(`  ... ${count}/${QUESTIONS.length}`);
  }
  console.log(`✅ ${count} questions seeded`);
  
  const total = await p.question.count();
  console.log(`\n🎉 Done! Total questions in DB: ${total}`);
}

main().catch(e => { console.error(e); process.exit(1); }).finally(() => p.$disconnect());
